language: php
script: phpunit --verbose --coverage-text

php:
  - 7.3
  - 7.4

before_script:
  - "composer install -v"


after_script:
  - "composer test-ci"
  - "CODECLIMATE_REPO_TOKEN=0f25cc624257cbdc2f5a89cf12776a18aca88fa9702091320e85cacdfa612fdf ./vendor/bin/test-reporter"
