language: php
script: composer test-ci

php:
  - 7.3
  - 7.4

before_script:
  - "composer install -v"


after_script:
  - "/vendor/bin/phpunit --testdox"
  - "/vendor/bin/phpunit --coverage-clover build/logs/clover.xml"
  - "CODECLIMATE_REPO_TOKEN=054ca06aaad2c4c0e1d57489c83709006f5472fa1c363b94476585adf909148f ./vendor/bin/test-reporter"
